---
# tasks file for ee_remote_image
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check if skopeo is installed
  assert:
    that:
      - "'skopeo' in ansible_facts.packages"
    success_msg: Skopeo is installed
    fail_msg: Skopeo must be installed before using role

- name: Interating through remote execution environment list
  include_tasks: add-remote.yml
  loop: "{{ ah_ee_remote_images }}"
...
