---
galaxy_info:
  author: "Jeff Kellam"
  description: "An Ansible Role to create remote ee images in Automation Hub."
  company: "Red Hat"

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: "GPLv3+"

  min_ansible_version: "2.9"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: "EL"
      versions:
        - "all"

  galaxy_tags:
    - "automationhub"
    - "galaxy"
    - "configuration"
    - "ee"
    - "registry"
    - "remote"

dependencies: []
# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
...
